baseURL = ""
languageCode = "en-us"
title = "Marzie e Simone sposi!"
theme = "hugo-stellar-theme"

[params]
  [params.header]
    title = ""
    description = 'Benvenuti sul sito del nostro matrimonio :D'
    image = "images/m&s.png"

  [[params.navigation]]
    name = "Introduzione"
    href = "#intro"

  [[params.navigation]]
    name = "Quando"
    href = "#quando"

  [[params.navigation]]
    name = "Viaggio di nozze"
    href = "#ViaggioDiNozze"

  [[params.navigation]]
    name = "Informazioni"
    href = "#informazioni"

    [params.intro]
        title = "Ipsum sed adipiscing"
        description = "Sed lorem ipsum dolor sit amet nullam consequat feugiat consequat magna adipiscing magna etiam amet veroeros. Lorem ipsum dolor tempus sit cursus. Tempus nisl et nullam lorem ipsum dolor sit amet aliquam."
        image = "images/pic01.jpg"
        
    [[params.section]]
    id = "quando"
    title = "Magna veroeros"
    description = ""

    [[params.section]]
    id = "ViaggioDiNozze"
    title = "Viaggio di nozze"
    description = "La meta del nostro viaggio di nozza sarà il Giappone! Inizieremo la nostra avventura atterrando a Tokyo il dd/mm/yyyy e proseguiremo il nostro viaggio toccando le città di city1, city2, city3 per poi rientrare in Italia il dd/mm/yyyy."

    [params.section.features]
      enable = true
      [[params.section.feature]]
        image = "images/JapanTravelMap.jpg"

      [[params.section.feature]]
        icon = "fa-copy"

      [[params.section.feature]]
        icon = "fa-diamond"

    [[params.section]]
    id = "informazioni"
    title = "Congue imperdiet"
    description = "Donec imperdiet consequat consequat. Suspendisse feugiat congue posuere. Nulla massa urna, fermentum eget quam aliquet."

    [params.footer]
    enable = true
    title = "Aliquam sed mauris"
    description = "Sed lorem ipsum dolor sit amet et nullam consequat feugiat consequat magna adipiscing tempus etiam dolore veroeros. eget dapibus mauris. Cras aliquet, nisl ut viverra sollicitudin, ligula erat egestas velit, vitae tincidunt odio."

    second_title = "Contattaci"
    email = "marziagallesio@gmail.com s.pupino91@gmail.com"

    # copyright
    [params.footer.copyright]
      enable = true
      text = "© marziaesimonesposi.com, Design [HTML5UP](https://html5up.net), Site builded with [HUGO](https://gohugo.io/), Hosted on [Netlify](https://www.netlify.com/)"